import type { InfrastructureProfile } from './types'

export const DEFAULT_PROFILE: InfrastructureProfile = {
  id: 'new',
  name: '',
  industry: 'Retail',
  description: '',
  createdAt: '2026-09-05T00:00:00.000Z',
  status: 'draft',
  servers: 6,
  vcpusPerServer: 4,
  ramGbPerServer: 16,
  avgCpuUtil: 45,
  avgMemUtil: 55,
  os: 'linux',
  containerized: false,
  database: 'mysql',
  dbSizeGb: 500,
  readHeavy: true,
  storageTb: 5,
  monthlyUsers: 100_000,
  peakRps: 800,
  trafficPattern: 'spiky',
  workloadType: 'web',
  edgeEnvironment: false,
  lowBandwidth: false,
  budgetUsd: 6000,
  availability: '99.99',
  rtoMinutes: 60,
  rpoMinutes: 15,
  performance: 'medium',
  security: 'medium',
  compliance: [],
  priorities: { cost: 40, availability: 20, security: 20, performance: 20 },
}

export const SAMPLE_PROJECTS: InfrastructureProfile[] = [
  {
    ...DEFAULT_PROFILE,
    id: 'retailco-erp',
    name: 'RetailCo Legacy E-Commerce',
    industry: 'Retail',
    description: 'PHP monolith on 6 rack servers with a 5 TB product-image NAS and MySQL 5.7 primary/replica.',
    createdAt: '2026-08-12T09:30:00.000Z',
    status: 'simulated',
  },
  {
    ...DEFAULT_PROFILE,
    id: 'finserve-core',
    name: 'FinServe Core Banking',
    industry: 'Financial Services',
    description: 'Oracle-backed Java core banking platform on Windows Server, PCI-DSS in scope, 24x7 SLA.',
    createdAt: '2026-08-20T14:10:00.000Z',
    status: 'analysed',
    servers: 14,
    vcpusPerServer: 16,
    ramGbPerServer: 128,
    avgCpuUtil: 38,
    avgMemUtil: 62,
    os: 'windows',
    database: 'oracle',
    dbSizeGb: 4200,
    readHeavy: false,
    storageTb: 40,
    monthlyUsers: 850_000,
    peakRps: 4200,
    trafficPattern: 'steady',
    workloadType: 'legacy',
    lowBandwidth: false,
    budgetUsd: 40_000,
    availability: '99.999',
    rtoMinutes: 5,
    rpoMinutes: 1,
    performance: 'high',
    security: 'high',
    compliance: ['PCI-DSS', 'SOC 2'],
    priorities: { cost: 10, availability: 40, security: 35, performance: 15 },
  },
  {
    ...DEFAULT_PROFILE,
    id: 'meditrack',
    name: 'MediTrack Patient Portal',
    industry: 'Healthcare',
    description: 'Containerised Node.js API with MongoDB, serving 12 rural clinics with unreliable connectivity.',
    createdAt: '2026-09-01T11:45:00.000Z',
    status: 'draft',
    servers: 4,
    vcpusPerServer: 8,
    ramGbPerServer: 32,
    avgCpuUtil: 30,
    avgMemUtil: 40,
    containerized: true,
    database: 'mongodb',
    dbSizeGb: 120,
    readHeavy: true,
    storageTb: 2,
    monthlyUsers: 35_000,
    peakRps: 300,
    trafficPattern: 'seasonal',
    workloadType: 'api',
    edgeEnvironment: true,
    lowBandwidth: true,
    budgetUsd: 3500,
    availability: '99.9',
    rtoMinutes: 30,
    rpoMinutes: 5,
    performance: 'medium',
    security: 'high',
    compliance: ['HIPAA'],
    priorities: { cost: 30, availability: 20, security: 40, performance: 10 },
  },
]

export const INDUSTRIES = [
  'Retail',
  'Financial Services',
  'Healthcare',
  'Manufacturing',
  'Education',
  'Media',
  'Logistics',
  'Government',
  'SaaS',
]

export const COMPLIANCE_OPTIONS = ['PCI-DSS', 'HIPAA', 'SOC 2', 'GDPR', 'ISO 27001']
